Local scratch location is updated
jade-hpc-gpu/docs pull request #36
Opened 2022-07-09 17:52 UTC by wizofe

Not sure if `local_scratch` needs to be also changed below for the creation of Singularity containers. Can you please double check?

2023-10-31 16:32 UTC, twinkarma requested changes
Just need to change `$USERID` to `$USER` and we should be good.

2023-10-31 16:32 UTC, twinkarma commented on jade/containers.rst
> +Any files you copy into ``/home_directory`` will have the same userid as normal and will be available once exiting the container. The local disk space on the node is available at: ``/raid/local_scrat
Looking good, additionally it should also be `$USER` and not `$USERID` which returns nothing.

```suggestion
Any files you copy into ``/home_directory`` will have the same userid as normal and will be available once exiting the container. The local disk space on the node is available at: ``/raid/local_scratch/$USER``
```

2023-10-31 16:46 UTC, twinkarma commented
I've just tested with a singularity container, it looks like the local scratch is not automatically mounted into the container. The `singbatch` and `singinteractive` commands are also missing. I'll raise an issue for this with Hartree.

2023-11-24 13:28 UTC, ericspod commented
Hi @twinkarma I think these changes and those in the other pending PR are good to be pushed, are you ok with me pushing this through and proposing some other documentation enhancements?

2023-11-24 14:36 UTC, twinkarma commented
Hi @ericspod I've made some change requests in the comments above but have not had any response. 

I've just gone and tried this again with both the docker images and singularity:

- Docker
  - the `/local_scratch` folder does exist but it doesn't seem to have been mounted properly as it should have a list of your username (in the python image)
  - echo of $USERID and $USER does not print username or user id as the user credentials were not mounted properly into the container
  - There's no `/raid` directory (in the python image)
- Singularity
  - Scratch is just not mounted by default, I'm chasing this up as it seems silly for this to not happen.
 
So for both Singularity and Docker, it would seem we'll have to mount the scratch drive manually. This should be trivial in singularity e.g. `singularity exec --bind /raid:/raid my_container.sif` and then you can access scratch in exactly the same way as form outside the container. Not sure about the docker images though, it might need some help from the admins.

2023-11-24 18:17 UTC, ericspod commented
Hi @twinkarma for this PR let's commit your suggestion and merge. @wizofe I hope you're ok with that and thanks for the help.

For the Docker and Singularity issues we can do things manually like you suggest and update docs to reflect that.

2023-11-27 14:54 UTC, twinkarma approved these changes
@wizofe @ericspod  Sorry for the hassle, just wanted to check that everything's been mounted properly.

2023-11-27 14:54 UTC, twinkarma commented on jade/containers.rst
> +Any files you copy into ``/home_directory`` will have the same userid as normal and will be available once exiting the container. The local disk space on the node is available at: ``/raid/local_scrat
Got a response from Hartree, looks like when using docker container, the scratch directory are mounted directly to `/local_scratch` and no username/id needs to be appended.

```suggestion
Any files you copy into ``/home_directory`` will have the same userid as normal and will be available once exiting the container. The local disk space on the node is available at: ``/local_scratch/``
```

2023-11-27 14:54 UTC, merged